#pragma once 

enum Words
{
    FILE_, OPEN, SAVE, SAVE_AS, EXIT, OPTIONS,
    THEME, LANGUAGE, HELP, HOW_TO, CREDITS,
    CHARGES, ADD_CHARGE, IGNORE_CHARGE, EDIT_CHARGE,
    REMOVE_CHARGE, TENSION, POTENTIAL, WORK, ENERGY,
    USE_CURSORPOSITION, POSITION, START_, DESTINATION,
    PLAY_, PAUSE_, SPEED_2_, EDIT_, ADDITIONAL, CAMERA_AT,
    DEFAULT, CHANGE_SCENE, SCALE, SHOW_GRID,
    SHOW_ELECTROSTATIC_FIELD, INFO,
    LENGTH_OF_WORDS_IN_DICT
};

enum Language
{
    EN,
    RUS,
    LENGTH_OF_LANGUAGES
};
